version : '3.1'

services: 
    adminer:
      image : adminer
      ports :
        - 8080:8080
    db:
      image : mysql:5.6
      environment : 
        - MYSQL_ROOT_PASSWORD=root  
      ports :
        - 3306:3306
  